imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    trusted_proxies: ~
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    http_method_override: true
    session:
        cookie_path:           /arts/stringensemble

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'IcsePublicBundle:Form:custom_fields.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    sass: /usr/bin/sass
    java: /usr/bin/java
    filters:
        cssrewrite: ~
        sass: ~
        scss: ~
        compass: ~
        yui_css:
            jar: /usr/share/java/yuicompressor.jar 
        #   jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar
        yui_js:
            jar: /usr/share/java/yuicompressor-2.4.7.jar 
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport:      %mailer_transport%
    host:           %mailer_host%
    username:       %mailer_user%
    password:       %mailer_password%
    encryption:     %mailer_encryption%
    sender_address: %mailer_sender_address% 

fkr_imagine:
    driver: imagick

fos_js_routing:
    routes_to_expose: [ IcsePublicBundle_query_username ] 

jms_serializer:
    handlers:
        datetime:
            default_format: "U000" # Unix timestamp