imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    trusted_proxies: ~
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    assets:
        version: 10
        version_format: %%s?v%%s
    default_locale:  %locale%
    http_method_override: true
    session:
        cookie_path: /
        cookie_lifetime: 0

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form_themes:
        - 'IcsePublicBundle:Form:custom_fields.html.twig'
        - 'IcseMembersBundle:Form:fields.html.twig'
    globals:
        facebook_page_id: %facebook_page_id%
        facebook_app_id: %facebook_app_id%
        home_url: %home_url%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    sass: /usr/bin/sass
    java: /usr/bin/java
    filters:
        cssrewrite: ~
        sass: ~
        scss: ~
        compass: ~
        uglifyjs2:
            bin: /usr/bin/uglifyjs
            mangle: true
        uglifycss:
            bin: /usr/bin/uglifycss

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport:      %mailer_transport%
    host:           %mailer_host%
    username:       %mailer_user%
    password:       %mailer_password%
    encryption:     %mailer_encryption%
    sender_address: %mailer_sender_address% 

fkr_imagine:
    driver: imagick

fos_js_routing:
    routes_to_expose: [ IcsePublicBundle_query_username, IcsePublicBundle_resource ]

jms_serializer:
    handlers:
        datetime:
            default_format: "U000" # Unix timestamp

acts_social_api:
    apis:
        facebook:
            client_id: %facebook_app_id%
            client_secret: %facebook_app_secret%
            paths:
                create_page_event:
                   path: /{page_id}/events
                   method: POST
                   arguments: [page_id, name, description, start_time, end_time, location, ticket_uri]
                   url_has_params: true
                update_event:
                   path: /{event_id}
                   method: PUT
                   arguments: [event_id, name, description, start_time, end_time, location, ticket_uri]
                   url_has_params: true
                delete_event:
                   path: /{event_id}
                   method: DELETE
                   arguments: [event_id]
                   url_has_params: true
        google:
            client_id: %google_id%
            client_secret: %google_secret%
#        twitter:
#            client_id: %twitter_key%
#            client_secret: %twitter_secret%
#            access_token: %twitter_token%
#            access_token_secret: %twitter_token_secret%