security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            imperial_form_login:
                login_path:  /login
                check_path:  /login_check
            logout:
                path: /logout
                target: /
            remember_me:
                key:      3Q18L=WtlR/=9$B 
                lifetime: 1209600 
                path:     /arts/stringensemble

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/members, roles: ROLE_USER }

    providers:
        main:
            entity: { class: IcseMembersBundle:Member }

    encoders:
        Icse\MembersBundle\Entity\Member: sha512

    factories:
        - "%kernel.root_dir%/../src/Icse/MembersBundle/Resources/config/security_factories.yml" 

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
