security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            imperial_form_login:
                login_path:  /login
                check_path:  /login_check
                default_target_path: /members 
            logout:
                path: /logout
                target: /
            remember_me:
                key:      %remember_me_key%
                lifetime: 1209600 
                path:     /
            switch_user: true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/members/superadmin, roles: ROLE_SUPER_ADMIN, requires_channel: https }
        - { path: ^/members/admin, roles: ROLE_ADMIN, requires_channel: https }
        - { path: ^/members(/|$), roles: ROLE_USER, requires_channel: https }

    providers:
        main:
            entity: { class: IcseMembersBundle:Member }

    encoders:
        Icse\MembersBundle\Entity\Member: sha512

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
