<?php

namespace Proxies\__CG__\Icse\PublicBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Subscriber extends \Icse\PublicBundle\Entity\Subscriber implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setLogin($login)
    {
        $this->__load();
        return parent::setLogin($login);
    }

    public function getLogin()
    {
        $this->__load();
        return parent::getLogin();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setFirstName($firstName)
    {
        $this->__load();
        return parent::setFirstName($firstName);
    }

    public function getFirstName()
    {
        $this->__load();
        return parent::getFirstName();
    }

    public function setLastName($lastName)
    {
        $this->__load();
        return parent::setLastName($lastName);
    }

    public function getLastName()
    {
        $this->__load();
        return parent::getLastName();
    }

    public function setDepartment($department)
    {
        $this->__load();
        return parent::setDepartment($department);
    }

    public function getDepartment()
    {
        $this->__load();
        return parent::getDepartment();
    }

    public function setPlayer($player)
    {
        $this->__load();
        return parent::setPlayer($player);
    }

    public function isPlayer()
    {
        $this->__load();
        return parent::isPlayer();
    }

    public function setInstrument($instrument)
    {
        $this->__load();
        return parent::setInstrument($instrument);
    }

    public function setOtherInstrument($instrument)
    {
        $this->__load();
        return parent::setOtherInstrument($instrument);
    }

    public function getInstrument()
    {
        $this->__load();
        return parent::getInstrument();
    }

    public function getOtherInstrument()
    {
        $this->__load();
        return parent::getOtherInstrument();
    }

    public function setStandard($standard)
    {
        $this->__load();
        return parent::setStandard($standard);
    }

    public function getStandard()
    {
        $this->__load();
        return parent::getStandard();
    }

    public function setSubscribedAt($subscribedAt)
    {
        $this->__load();
        return parent::setSubscribedAt($subscribedAt);
    }

    public function getSubscribedAt()
    {
        $this->__load();
        return parent::getSubscribedAt();
    }

    public function getPlayer()
    {
        $this->__load();
        return parent::getPlayer();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'login', 'email', 'first_name', 'last_name', 'department', 'player', 'instrument', 'standard', 'subscribed_at');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}