<?php

namespace Proxies\__CG__\Icse\PublicBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class PieceOfMusic extends \Icse\PublicBundle\Entity\PieceOfMusic implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setUpdatedAt($updatedAt)
    {
        $this->__load();
        return parent::setUpdatedAt($updatedAt);
    }

    public function getUpdatedAt()
    {
        $this->__load();
        return parent::getUpdatedAt();
    }

    public function setUpdatedBy($updatedBy)
    {
        $this->__load();
        return parent::setUpdatedBy($updatedBy);
    }

    public function getUpdatedBy()
    {
        $this->__load();
        return parent::getUpdatedBy();
    }

    public function addPerformance(\Icse\PublicBundle\Entity\PerformanceOfAPiece $performances)
    {
        $this->__load();
        return parent::addPerformance($performances);
    }

    public function removePerformance(\Icse\PublicBundle\Entity\PerformanceOfAPiece $performances)
    {
        $this->__load();
        return parent::removePerformance($performances);
    }

    public function getPerformances()
    {
        $this->__load();
        return parent::getPerformances();
    }

    public function setComposer($composer)
    {
        $this->__load();
        return parent::setComposer($composer);
    }

    public function getComposer()
    {
        $this->__load();
        return parent::getComposer();
    }

    public function addPracticePart(\Icse\MembersBundle\Entity\PracticePart $practiceParts)
    {
        $this->__load();
        return parent::addPracticePart($practiceParts);
    }

    public function removePracticePart(\Icse\MembersBundle\Entity\PracticePart $practiceParts)
    {
        $this->__load();
        return parent::removePracticePart($practiceParts);
    }

    public function getPracticeParts()
    {
        $this->__load();
        return parent::getPracticeParts();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'composer', 'name', 'updated_at', 'updated_by', 'performances', 'practice_parts');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}