Icse\PublicBundle\Entity\Event:
    type: entity
    repositoryClass: Icse\PublicBundle\Entity\EventRepository
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        description:
            type: text
            nullable: true
        starts_at:
            type: datetime
            nullable: true 
        updated_at:
            type: datetime
    manyToOne:
        location:
            targetEntity: Venue
            nullable: true 
        poster:
            targetEntity: Image
            nullable: true
        updated_by:
            targetEntity: Icse\MembersBundle\Entity\Member
    oneToMany:
        performances:
            targetEntity: PerformanceOfAPiece
            mappedBy: event 
    lifecycleCallbacks: {  }

