Icse\PublicBundle\Entity\Image:
    type: entity
    table: null
    repositoryClass: Icse\PublicBundle\Entity\ImageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        file_extension:
            type: string
            length: 10
        name:
            type: string
            length: 255
        category:
            type: string
            length: 255
            nullable: true
        width:
            type: integer
        height:
            type: integer
        legacy_name:
            type: string
            length: 255
            nullable: true
        updated_at:
            type: datetime
    manyToOne:
        updated_by:
            targetEntity: Icse\MembersBundle\Entity\Member
            joinColumn:
                nullable: false
    lifecycleCallbacks:
        postPersist: [upload]
        preRemove: [storeFilenameForRemove]
        postRemove: [removeUpload]
