Icse\PublicBundle\Entity\PerformanceOfAPiece:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        sort_index:
            type: integer
    manyToOne:
        piece:
            targetEntity: PieceOfMusic
            inversedBy: performances
            joinColumn:
                nullable: false
        event:
            targetEntity: Event
            inversedBy: performances
            joinColumn:
                nullable: false
    lifecycleCallbacks: {  }
