Icse\PublicBundle\Entity\PieceOfMusic:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        composer:
            type: string
            length: 255
        name:
            type: string
            length: 255
        updated_at:
            type: datetime
    oneToMany:
        performances:
            targetEntity: PerformanceOfAPiece
            mappedBy: piece
        practice_parts:
            targetEntity: Icse\MembersBundle\Entity\PracticePart 
            mappedBy: piece
    manyToOne:
        updated_by:
            targetEntity: Icse\MembersBundle\Entity\Member
            joinColumn:
                nullable: false
    lifecycleCallbacks: {  }
