Icse\PublicBundle\Entity\PieceOfMusic:
    type: entity
    repositoryClass: Icse\PublicBundle\Entity\PieceOfMusicRepository
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        composer:
            type: string
            length: 255
        name:
            type: string
            length: 255
        updated_at:
            type: datetime
    oneToMany:
        performances:
            targetEntity: PerformanceOfAPiece
            mappedBy: piece
        practice_parts:
            targetEntity: Icse\MembersBundle\Entity\PracticePart 
            mappedBy: piece
            orderBy:
                sort_index: ASC
    manyToOne:
        updated_by:
            targetEntity: Icse\MembersBundle\Entity\Member
            joinColumn:
                nullable: false
    lifecycleCallbacks: {  }
