Icse\PublicBundle\Entity\Venue:
    type: entity
    table: null
    repositoryClass: Icse\PublicBundle\Entity\VenueRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        address:
            type: text
            nullable: true
        embedMap:
            type: text
            nullable: true
        updated_at:
            type: datetime
        manyToOne:
            updated_by: 
                targetEntity: Member
    lifecycleCallbacks: {  }
