<?php

namespace Icse\MembersBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommitteeRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommitteeRoleRepository extends EntityRepository
{
    public function findCurrent(\DateTime $dt = null)
    {
        if ($dt === null) $dt = new \DateTime;
        $current_month = intval($dt->format("m"));
        $current_year = intval($dt->format("Y"));

        if ($current_month < 8) $start_year = $current_year - 1;
        else $start_year = $current_year;

        return $this->getEntityManager()
                    ->createQuery ('SELECT r
                                    FROM IcseMembersBundle:CommitteeRole r
                                    WHERE r.start_year = :year
                                    ORDER BY r.sort_index ASC')
                    ->setParameters(['year' => $start_year])
                    ->getResult();
    }
}
