<?php

namespace Icse\MembersBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommitteeRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommitteeRoleRepository extends EntityRepository
{
    public function findCurrent(\DateTime $dt = null)
    {
        if ($dt === null) $dt = new \DateTime;
        $current_month = intval($dt->format("m"));
        $current_year = intval($dt->format("Y"));

        if ($current_month < 8) $start_year = $current_year - 1;
        else $start_year = $current_year;

        return $this->getEntityManager()
                    ->createQuery ('SELECT r
                                    FROM IcseMembersBundle:CommitteeRole r
                                    WHERE r.start_year = :year
                                    ORDER BY r.sort_index ASC')
                    ->setParameters(['year' => $start_year])
                    ->getResult();
    }

    public function findByUsernameAndYear($username, $start_year)
    {
        return $this
            ->getEntityManager()
            ->createQuery ('
                SELECT r
                FROM IcseMembersBundle:CommitteeRole r
                JOIN r.member m
                WHERE r.start_year = :year
                AND m.username = :username
            ')
            ->setParameters([
                'year' => $start_year,
                'username' => $username,
            ])
            ->getResult();
    }

    public function getMaxSortIndexForYear($year)
    {
        $result = $this
            ->getEntityManager()
            ->createQuery ('
                SELECT COUNT(r.sort_index), MAX(r.sort_index)
                FROM IcseMembersBundle:CommitteeRole r
                WHERE r.start_year = :year
            ')
            ->setParameters(['year' => $year])
            ->getSingleResult();

        $count      = $result[1];
        $sort_index = $result[2];

        return $count ? $sort_index : -1;
    }
}
