<?php

namespace Icse\MembersBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommitteeRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommitteeRoleRepository extends EntityRepository
{
    public function maxSortPositionOfYear($year)
    {
        return $this->getEntityManager()
                    ->createQuery ('SELECT MAX(r.sort_position)
                                    FROM IcseMembersBundle:CommitteeRole r
                                    WHERE r.start_year = :year')
                    ->setParameters(['year' => $year])
                    ->getSingleScalarResult();
    }
}
