<?php

namespace Icse\MembersBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RehearsalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RehearsalRepository extends EntityRepository
{
    public function findNext()
    {
        return $this->getEntityManager()
                    ->createQuery('SELECT r
                                   FROM IcseMembersBundle:Rehearsal r
                                   WHERE r.starts_at >= :starttime
                                   ORDER BY r.starts_at ASC')
                    ->setParameters(array('starttime' => new \DateTime("today")))
                    ->setMaxResults(1)
                    ->getOneOrNullResult();
    }

    public function findNextN($n=1)
    {
        return $this->getEntityManager()
                    ->createQuery('SELECT r
                                   FROM IcseMembersBundle:Rehearsal r
                                   WHERE r.starts_at >= :starttime
                                   ORDER BY r.starts_at ASC')
                    ->setParameters(array('starttime' => new \DateTime("today")))
                    ->setMaxResults($n)
                    ->getResult();
    }
}
