<?php

namespace Icse\MembersBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SentNewsletter Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SentNewsletterRepository extends EntityRepository
{
    public function findLastNToMailinglist($n=1)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT n
                           FROM IcseMembersBundle:SentNewsletter n
                           WHERE n.dest = :dest_id
                           ORDER BY n.sent_at DESC')
            ->setParameter('dest_id', SentNewsletter::DEST_MAILINGLIST)
            ->setMaxResults($n)
            ->getResult();
    }
}
