<?php

namespace Icse\MembersBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SentNewsletter Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SentNewsletterRepository extends EntityRepository
{
}
