<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121018003838 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE PracticePart ADD piece_id INT DEFAULT NULL, ADD file VARCHAR(255) NOT NULL, ADD type VARCHAR(255) NOT NULL, ADD updated_at DATETIME NOT NULL, ADD updated_by INT NOT NULL");
        $this->addSql("ALTER TABLE PracticePart ADD CONSTRAINT FK_9BD4B60FC40FCFA8 FOREIGN KEY (piece_id) REFERENCES PieceOfMusic (id)");
        $this->addSql("CREATE INDEX IDX_9BD4B60FC40FCFA8 ON PracticePart (piece_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE PracticePart DROP FOREIGN KEY FK_9BD4B60FC40FCFA8");
        $this->addSql("DROP INDEX IDX_9BD4B60FC40FCFA8 ON PracticePart");
        $this->addSql("ALTER TABLE PracticePart DROP piece_id, DROP file, DROP type, DROP updated_at, DROP updated_by");
    }
}
