<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121228205826 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE NewsArticle DROP FOREIGN KEY FK_3E819CDA65FF1AEC");
        $this->addSql("DROP INDEX IDX_3E819CDA65FF1AEC ON NewsArticle");
        $this->addSql("ALTER TABLE NewsArticle CHANGE updatedby_id updated_by_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE NewsArticle ADD CONSTRAINT FK_3E819CDA896DBBDE FOREIGN KEY (updated_by_id) REFERENCES Member (id)");
        $this->addSql("CREATE INDEX IDX_3E819CDA896DBBDE ON NewsArticle (updated_by_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE NewsArticle DROP FOREIGN KEY FK_3E819CDA896DBBDE");
        $this->addSql("DROP INDEX IDX_3E819CDA896DBBDE ON NewsArticle");
        $this->addSql("ALTER TABLE NewsArticle CHANGE updated_by_id updatedBy_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE NewsArticle ADD CONSTRAINT FK_3E819CDA65FF1AEC FOREIGN KEY (updatedBy_id) REFERENCES Member (id)");
        $this->addSql("CREATE INDEX IDX_3E819CDA65FF1AEC ON NewsArticle (updatedBy_id)");
    }
}
