<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120402231444 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE Member (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(50) NOT NULL, salt VARCHAR(40) NOT NULL, password VARCHAR(40) NOT NULL, email VARCHAR(60) NOT NULL, active TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_7748FF4EF85E0677 (username), UNIQUE INDEX UNIQ_7748FF4EE7927C74 (email), PRIMARY KEY(id)) ENGINE = InnoDB");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE Member");
    }
}
