<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121005011306 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE PieceOfMusic (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, updated_at DATETIME NOT NULL, updated_by INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE PerformanceOfAPiece (id INT AUTO_INCREMENT NOT NULL, piece_id INT DEFAULT NULL, event_id INT DEFAULT NULL, INDEX IDX_BC40337C40FCFA8 (piece_id), INDEX IDX_BC4033771F7E88B (event_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE PracticePart (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE PerformanceOfAPiece ADD CONSTRAINT FK_BC40337C40FCFA8 FOREIGN KEY (piece_id) REFERENCES PieceOfMusic (id)");
        $this->addSql("ALTER TABLE PerformanceOfAPiece ADD CONSTRAINT FK_BC4033771F7E88B FOREIGN KEY (event_id) REFERENCES Event (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE PerformanceOfAPiece DROP FOREIGN KEY FK_BC40337C40FCFA8");
        $this->addSql("DROP TABLE PieceOfMusic");
        $this->addSql("DROP TABLE PerformanceOfAPiece");
        $this->addSql("DROP TABLE PracticePart");
    }
}
