<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120404155900 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Member ADD first_name VARCHAR(50) NOT NULL, ADD last_name VARCHAR(50) NOT NULL, CHANGE salt salt VARCHAR(40) DEFAULT NULL, CHANGE password password VARCHAR(89) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Member DROP first_name, DROP last_name, CHANGE salt salt VARCHAR(40) NOT NULL, CHANGE password password VARCHAR(89) NOT NULL");
    }
}
