<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121228182459 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE NewsArticle (id INT AUTO_INCREMENT NOT NULL, picture_id INT DEFAULT NULL, headline VARCHAR(255) NOT NULL, subhead VARCHAR(255) DEFAULT NULL, body LONGTEXT NOT NULL, posted_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, updated_by INT NOT NULL, INDEX IDX_3E819CDAEE45BDBF (picture_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE NewsArticle ADD CONSTRAINT FK_3E819CDAEE45BDBF FOREIGN KEY (picture_id) REFERENCES Image (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE NewsArticle");
    }
}
