<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130522222223 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Rehearsal ADD updated_by_id INT DEFAULT NULL, DROP updated_by");
        $this->addSql("ALTER TABLE Rehearsal ADD CONSTRAINT FK_C9F7D89C896DBBDE FOREIGN KEY (updated_by_id) REFERENCES Member (id)");
        $this->addSql("CREATE INDEX IDX_C9F7D89C896DBBDE ON Rehearsal (updated_by_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Rehearsal DROP FOREIGN KEY FK_C9F7D89C896DBBDE");
        $this->addSql("DROP INDEX IDX_C9F7D89C896DBBDE ON Rehearsal");
        $this->addSql("ALTER TABLE Rehearsal ADD updated_by INT NOT NULL, DROP updated_by_id");
    }
}
