<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121017014937 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE Venue (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE Rehearsal ADD location_id INT DEFAULT NULL, DROP location");
        $this->addSql("ALTER TABLE Rehearsal ADD CONSTRAINT FK_C9F7D89C64D218E FOREIGN KEY (location_id) REFERENCES Venue (id)");
        $this->addSql("CREATE INDEX IDX_C9F7D89C64D218E ON Rehearsal (location_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Rehearsal DROP FOREIGN KEY FK_C9F7D89C64D218E");
        $this->addSql("DROP TABLE Venue");
        $this->addSql("ALTER TABLE Rehearsal DROP FOREIGN KEY FK_C9F7D89C64D218E");
        $this->addSql("DROP INDEX IDX_C9F7D89C64D218E ON Rehearsal");
        $this->addSql("ALTER TABLE Rehearsal ADD location VARCHAR(255) DEFAULT NULL, DROP location_id");
    }
}
