IcsePublicBundle_home:
    pattern:  /
    defaults: { _controller: IcsePublicBundle:Default:index }

IcsePublicBundle_about:
    pattern:  /about
    defaults: { _controller: IcsePublicBundle:Default:about }

IcsePublicBundle_event:
    pattern:  /events/{id}/{slug}
    defaults: {_controller: IcsePublicBundle:Events:event, slug: ''}

IcsePublicBundle_join:
    pattern:  /join
    defaults: { _controller: IcsePublicBundle:SignUp:join, freshers: false }

IcsePublicBundle_join_freshers:
    pattern:  /join/freshersfair
    defaults: { _controller: IcsePublicBundle:SignUp:join, freshers: true }

IcsePublicBundle_signup_results_tmp:
    pattern:  /view/all/signups/from/freshers/fair
    defaults: { _controller: IcsePublicBundle:Default:signup}results }

IcsePublicBundle_query_username:
    pattern:  /join/query_username
    defaults: { _controller: IcsePublicBundle:SignUp:query_username, _format: json }

IcsePublicBundle_support:
    pattern:  /support
    defaults: { _controller: IcsePublicBundle:Default:support }

IcsePublicBundle_contact:
    pattern:  /contact
    defaults: { _controller: IcsePublicBundle:Default:contact }

IcsePublicBundle_login:
    pattern:   /login
    defaults:  { _controller: IcsePublicBundle:Security:login }

IcsePublicBundle_login_check:
    pattern:   /login_check

IcsePublicBundle_resource:
    pattern:   /resources/{type}/{file}
    defaults: { _controller: IcsePublicBundle:Resources:resource }
