IcsePublicBundle_home:
    pattern:  /
    defaults: { _controller: IcsePublicBundle:Default:index }

IcsePublicBundle_news:
    pattern:  /news
    defaults: { _controller: IcsePublicBundle:News:index } 

IcsePublicBundle_news_article:
    pattern:  /news/{id}/{slug}
    defaults: {_controller: IcsePublicBundle:News:article, slug: ''}

IcsePublicBundle_news_article_endslash:
    pattern:  /event/{id}/
    defaults: {_controller: IcsePublicBundle:News:article, slug: ''}

IcsePublicBundle_about:
    pattern:  /about/ensemble
    defaults: { _controller: IcsePublicBundle:About:ensemble }

IcsePublicBundle_about_ensemble:
    pattern:  /about/ensemble
    defaults: { _controller: IcsePublicBundle:About:ensemble }

IcsePublicBundle_about_conductor:
    pattern:  /about/conductor
    defaults: { _controller: IcsePublicBundle:About:conductor }

IcsePublicBundle_about_committee:
    pattern:  /about/committee
    defaults: { _controller: IcsePublicBundle:About:committee }

IcsePublicBundle_events:
    pattern:  /events/upcoming
    defaults: {_controller: IcsePublicBundle:Events:futureEventsIndex }

IcsePublicBundle_future_events:
    pattern:  /events/upcoming
    defaults: {_controller: IcsePublicBundle:Events:futureEventsIndex }

IcsePublicBundle_past_events:
    pattern:  /events/past
    defaults: {_controller: IcsePublicBundle:Events:pastEventsIndex }

IcsePublicBundle_past_events_in_year:
    pattern:  /events/past/in{year}
    defaults: {_controller: IcsePublicBundle:Events:pastEventsInYear }

IcsePublicBundle_event:
    pattern:  /event/{id}/{slug}
    defaults: {_controller: IcsePublicBundle:Events:event, slug: ''}

IcsePublicBundle_event_endslash:
    pattern:  /event/{id}/
    defaults: {_controller: IcsePublicBundle:Events:event, slug: ''}

IcsePublicBundle_join:
    pattern:  /join
    defaults: { _controller: IcsePublicBundle:SignUp:join, freshers: false }

IcsePublicBundle_join_freshers:
    pattern:  /join/freshersfair
    defaults: { _controller: IcsePublicBundle:SignUp:join, freshers: true }

IcsePublicBundle_signup_results_tmp:
    pattern:  /view/all/signups/from/freshers/fair
    defaults: { _controller: IcsePublicBundle:Default:signup_results }

IcsePublicBundle_query_username:
    pattern:  /join/query_username
    defaults: { _controller: IcsePublicBundle:SignUp:query_username, _format: json }

IcsePublicBundle_support:
    pattern:  /support
    defaults: { _controller: IcsePublicBundle:Default:support }

IcsePublicBundle_contact:
    pattern:  /contact
    defaults: { _controller: IcsePublicBundle:Default:contact }

IcsePublicBundle_login:
    pattern:   /login
    defaults:  { _controller: IcsePublicBundle:Security:login }

IcsePublicBundle_login_check:
    pattern:   /login_check

IcsePublicBundle_resource:
    pattern:   /resources/{type}/{file}
    defaults: { _controller: IcsePublicBundle:Resources:resource }
    requirements: 
        file: "[^\.]*\.?[^\.]*" # Directory traversal protection, but slashes allowed
