IcsePublicBundle_home:
    pattern:  /
    defaults: { _controller: IcsePublicBundle:Default:index }

IcsePublicBundle_about:
    pattern:  /about
    defaults: { _controller: IcsePublicBundle:Default:about }

IcsePublicBundle_join:
    pattern:  /join
    defaults: { _controller: IcsePublicBundle:SignUp:join }

IcsePublicBundle_join_success:
    pattern:  /join/success/{name}
    defaults: { _controller: IcsePublicBundle:SignUp:join_success }

IcsePublicBundle_query_username:
    pattern:  /join/query_username
    defaults: { _controller: IcsePublicBundle:SignUp:query_username, _format: json }

IcsePublicBundle_support:
    pattern:  /support
    defaults: { _controller: IcsePublicBundle:Default:support }

IcsePublicBundle_contact:
    pattern:  /contact
    defaults: { _controller: IcsePublicBundle:Default:contact }

IcsePublicBundle_login:
    pattern:   /login
    defaults:  { _controller: IcsePublicBundle:Security:login }

IcsePublicBundle_login_check:
    pattern:   /login_check
