Icse\PublicBundle\Entity\Subscriber:
    properties:
        first_name:
            - NotBlank: ~
        last_name:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email:
                message: Not a valid email address
                checkMX: true 
        player:
            - NotBlank: ~
