Icse\PublicBundle\Entity\Subscriber:
    constraints:
        - Callback: [validatePlayerInfo]
    properties:
        first_name:
            - NotBlank: ~
        last_name:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email:
                message: Not a valid email address
                checkMX: true
        player:
            - NotBlank: ~
Icse\PublicBundle\Entity\PieceOfMusic:
    properties:
        name:
            - NotBlank: ~
        composer:
            - NotBlank: ~

