Icse\MembersBundle\Entity\PracticePart:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        instrument:
            type: string
            length: 255
        sort_index:
            type: integer
    manyToOne:
        piece:
            targetEntity: Icse\PublicBundle\Entity\PieceOfMusic
            inversedBy: practice_parts
            joinColumn:
                nullable: false
    lifecycleCallbacks:
        postPersist: [upload]
        preRemove: [storeFilenameForRemove]
        postRemove: [removeUpload]