Icse\MembersBundle\Entity\Rehearsal:
    type: entity
    table: null
    repositoryClass: Icse\MembersBundle\Entity\RehearsalRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
            nullable: true
        comments:
            type: text
            nullable: true
        starts_at:
            type: datetime
        updated_at:
            type: datetime
    manyToOne:
        location:
            targetEntity: Icse\PublicBundle\Entity\Venue
            joinColumn:
                nullable: true
        updated_by: 
            targetEntity: Member
            joinColumn:
                nullable: false
    lifecycleCallbacks: {  }
