<?php

namespace Icse\PublicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
    public function findSlideshowImages($n = null)
    {
        $images = $this->findBy(['in_slideshow' => true]);
        if (is_null($n))
        {
            return $images;
        }
        else
        {
            shuffle($images);
            return array_slice($images, 0, $n);
        }
    }
}
