<?php

namespace Icse\PublicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PieceOfMusicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PieceOfMusicRepository extends EntityRepository
{
    public function findOneByIdWithIdIndexedPracticeParts($id)
    {
        return $this->getEntityManager()
            ->createQuery ('
                SELECT piece, part
                FROM IcsePublicBundle:PieceOfMusic piece
                LEFT JOIN  piece.practice_parts part INDEX BY part.id
                WHERE piece.id = :id
            ')
            ->setParameter('id', $id)
            ->getOneOrNullResult();
    }
}
