<?php

namespace Icse\PublicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SiteTextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteTextRepository extends EntityRepository
{


}
