IcseMembersBundle_return:
    pattern:  /members/return
    defaults: { _controller: IcseMembersBundle:Default:returnToLastPage }

IcseMembersBundle_home:
    pattern:  /members
    defaults: { _controller: IcseMembersBundle:Default:index }

IcseMembersBundle_calendar:
    pattern:  /members/calendar
    defaults: { _controller: IcseMembersBundle:Default:calendar }

IcseMembersBundle_practice_parts:
    pattern:  /members/practiceparts
    defaults: { _controller: IcseMembersBundle:PracticeParts:legacy }

IcseMembersBundle_logout: # Don't change this without changing listener!
    pattern:   /logout

IcseMembersBundle_account_settings:
    pattern:  /members/account
    defaults: { _controller: IcseMembersBundle:AccountSettings:index }

# Images
IcseMembersBundle_image_uploads:
    pattern:  /members/admin/images
    defaults: { _controller: IcseMembersBundle:Admin/Image:imageUploads }

IcseMembersBundle_receive_upload:
    pattern:  /members/admin/upload
    defaults: { _controller: IcseMembersBundle:Admin/Image:upload }

IcseMembersBundle_confirm_upload:
    pattern:  /members/admin/uploadconfirm
    defaults: { _controller: IcseMembersBundle:Admin/Image:confirmUpload }

# Rehearsal Admin #
IcseMembersBundle_rehearsaladmin:
    pattern:  /members/admin/rehearsals/{arg}
    defaults: { _controller: IcseMembersBundle:Admin/Rehearsal:router, arg: ~ }

# Venue Admin #
IcseMembersBundle_venueadmin:
    pattern:  /members/admin/venues/{arg}
    defaults: { _controller: IcseMembersBundle:Admin/Venue:router, arg: ~ }

# Members List #
IcseMembersBundle_members:
    pattern:  /members/superadmin/members/{arg}
    defaults: { _controller: IcseMembersBundle:SuperAdmin/Members:router, arg: ~ }

# Signup List #
IcseMembersBundle_signuplist:
    pattern:  /members/admin/signups/{arg}
    defaults: { _controller: IcseMembersBundle:Admin/SignupList:router, arg: ~ }

# Misc SuperAdmin #
IcseMembersBundle_site_dev:
    pattern:  /members/superadmin/sitedev
    defaults: { _controller: IcseMembersBundle:SuperAdmin/Misc:siteDev }

IcseMembersBundle_migrateDB:
    pattern:  /GoCscz3ALKBaq4TReRK9HKvaIB8If1UnnuATePZQ/migratedb
    defaults: { _controller: IcseMembersBundle:SuperAdmin/Misc:migrateDB }

IcseMembersBundle_testEmail:
    pattern:  /members/superadmin/testemail
    defaults: { _controller: IcseMembersBundle:SuperAdmin/Misc:testEmail }

IcseMembersBundle_test:
    pattern:  /members/superadmin/test
    defaults: { _controller: IcseMembersBundle:SuperAdmin/Misc:test }
