IcseMembersBundle_return:
    pattern:  /members/return
    defaults: { _controller: IcseMembersBundle:Default:returnToLastPage }

IcseMembersBundle_home:
    pattern:  /members
    defaults: { _controller: IcseMembersBundle:Default:index }

IcseMembersBundle_past_newsletters:
    pattern:  /members/newsletters
    defaults: { _controller: IcseMembersBundle:PastNewsletters:index }

IcseMembersBundle_calendar:
    pattern:  /members/calendar
    defaults: { _controller: IcseMembersBundle:Default:calendar }

IcseMembersBundle_practice_parts:
    pattern:  /members/practiceparts
    defaults: { _controller: IcseMembersBundle:PracticeParts:index }

IcseMembersBundle_logout:
    pattern:   /logout

IcseMembersBundle_account_settings:
    pattern:  /members/account
    defaults: { _controller: IcseMembersBundle:AccountSettings:index }

IcseMembersBundle_my_profile:
    pattern:  /members/myprofile
    defaults: { _controller: IcseMembersBundle:AccountSettings:profile }

# Admin
IcseMembersBundle_imageadmin:
    pattern:  /members/admin/images/{arg}
    defaults: { _controller: IcseMembersBundle:Admin/Image:router, arg: ~ }

IcseMembersBundle_rehearsaladmin:
    pattern:  /members/admin/rehearsals/{arg}
    defaults: { _controller: IcseMembersBundle:Admin/Rehearsal:router, arg: ~ }

IcseMembersBundle_newsadmin:
    pattern:  /members/admin/news/{arg}
    defaults: { _controller: IcseMembersBundle:Admin/News:router, arg: ~ }

IcseMembersBundle_eventadmin:
    pattern:  /members/admin/events/{arg}
    defaults: { _controller: IcseMembersBundle:Admin/Event:router, arg: ~ }

IcseMembersBundle_venueadmin:
    pattern:  /members/admin/venues/{arg}
    defaults: { _controller: IcseMembersBundle:Admin/Venue:router, arg: ~ }

IcseMembersBundle_musicadmin:
    pattern:  /members/admin/music/{arg}
    defaults: { _controller: IcseMembersBundle:Admin/Music:router, arg: ~ }

IcseMembersBundle_membersadmin:
    pattern:  /members/superadmin/members/{arg}
    defaults: { _controller: IcseMembersBundle:SuperAdmin/Members:router, arg: ~ }

IcseMembersBundle_committee_edit:
    pattern:  /members/superadmin/committee/{arg}
    defaults: { _controller: IcseMembersBundle:SuperAdmin/Committee:router, arg: ~ }

IcseMembersBundle_signuplist:
    pattern:  /members/admin/signups/{arg}
    defaults: { _controller: IcseMembersBundle:Admin/SignupList:router, arg: ~ }

IcseMembersBundle_sendemail:
    pattern:  /members/admin/email/{arg}
    defaults: { _controller: IcseMembersBundle:Admin/Email:router, arg: ~ }

# Misc SuperAdmin #
IcseMembersBundle_site_dev:
    pattern:  /members/superadmin/sitedev
    defaults: { _controller: IcseMembersBundle:SuperAdmin/Misc:siteDev }

IcseMembersBundle_migrateDB:
    pattern:  /migratedb
    defaults: { _controller: IcseMembersBundle:SuperAdmin/Misc:migrateDB }

IcseMembersBundle_phpinfo:
    pattern:  /phpinfo
    defaults: { _controller: IcseMembersBundle:SuperAdmin/Misc:phpinfo }

IcseMembersBundle_linkappcache:
    pattern:  /members/superadmin/linkappcache
    defaults: { _controller: IcseMembersBundle:SuperAdmin/Misc:appcache }

IcseMembersBundle_zipdir:
    pattern:  /members/superadmin/zipdir/{source_path}
    defaults: { _controller: IcseMembersBundle:SuperAdmin/Misc:zipDir }
    requirements:
        source_path: "[^\.]*\.?[^\.]*"

IcseMembersBundle_test:
    pattern:  /members/superadmin/test
    defaults: { _controller: IcseMembersBundle:SuperAdmin/Misc:test }
