IcseMembersBundle_home:
    pattern:  /members
    defaults: { _controller: IcseMembersBundle:Default:index }

IcseMembersBundle_logout:
    pattern:   /logout

IcseMembersBundle_account_settings:
    pattern:  /members/account
    defaults: { _controller: IcseMembersBundle:AccountSettings:index }
