IcseMembersBundle_home:
    pattern:  /members
    defaults: { _controller: IcseMembersBundle:Default:index }

IcseMembersBundle_practice_parts:
    pattern:  /members/practiceparts
    defaults: { _controller: IcseMembersBundle:Default:index }

IcseMembersBundle_logout:
    pattern:   /logout

IcseMembersBundle_account_settings:
    pattern:  /members/account
    defaults: { _controller: IcseMembersBundle:AccountSettings:index }

#Admin
IcseMembersBundle_image_uploads:
    pattern:  /members/admin/images
    defaults: { _controller: IcseMembersBundle:Admin:imageUploads }

IcseMembersBundle_receive_upload:
    pattern:  /members/admin/upload
    defaults: { _controller: IcseMembersBundle:Admin:upload }

IcseMembersBundle_confirm_upload:
    pattern:  /members/admin/uploadconfirm
    defaults: { _controller: IcseMembersBundle:Admin:confirmUpload }

# Members List #
IcseMembersBundle_members:
    pattern:  /members/superadmin/members
    defaults: { _controller: IcseMembersBundle:SuperAdmin/Members:index }
    requirements:
        _method: GET 

IcseMembersBundle_members_table:
    pattern:  /members/superadmin/members/table
    defaults: { _controller: IcseMembersBundle:SuperAdmin/Members:table }
    requirements:
        _method: GET 

IcseMembersBundle_members_create:
    pattern:  /members/superadmin/members
    defaults: { _controller: IcseMembersBundle:SuperAdmin/Members:create }
    requirements:
        _method: POST

IcseMembersBundle_members_update:
    pattern:  /members/superadmin/members/{id}
    defaults: { _controller: IcseMembersBundle:SuperAdmin/Members:update }
    requirements:
        _method: PUT 

IcseMembersBundle_members_delete:
    pattern:  /members/superadmin/members/{id}
    defaults: { _controller: IcseMembersBundle:SuperAdmin/Members:delete }
    requirements:
        _method: DELETE 

# Misc SuperAdmin #
IcseMembersBundle_site_dev:
    pattern:  /members/superadmin/sitedev
    defaults: { _controller: IcseMembersBundle:SuperAdmin/Misc:siteDev }

IcseMembersBundle_migrateDB:
    pattern:  /migratedb
    defaults: { _controller: IcseMembersBundle:SuperAdmin/Misc:migrateDB }

IcseMembersBundle_testEmail:
    pattern:  /members/superadmin/testemail
    defaults: { _controller: IcseMembersBundle:SuperAdmin/Misc:testEmail }
