parameters:
#    icse_members.example.class: Icse\MembersBundle\Example

services:
    lrotherfield.form.type.hidden_entity:
        class: Lrotherfield\Component\Form\Type\HiddenEntityType
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: form.type, alias: hidden_entity }

    security.authentication.provider.imperial:
        class: Icse\MembersBundle\Security\Authentication\Provider\ImperialProvider
        arguments: ['', @security.user_checker, '', @security.encoder_factory, %security.authentication.hide_user_not_found%]

    icse.twig.table_utils:
        class: Icse\MembersBundle\Twig\TableUtils
        tags:
            - { name: twig.extension } 

    kernel.listener.last_online_at_listener:
        class: Icse\MembersBundle\EventListener\LastOnlineAtListener
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onTerminate }
        arguments: [@security.context, @doctrine.orm.entity_manager] 

    icse.mailer:
        class: Icse\MembersBundle\Service\IcseMailer
        arguments: [@mailer, @css_to_inline_email_converter, %kernel.root_dir%] 

    ajax_response_gen:
        class: Icse\MembersBundle\Service\AjaxResponseGenerator
        arguments: [@jms_serializer]

    icse.calendar_events:
        class: Icse\MembersBundle\Service\CalendarEvents
        arguments: [@doctrine.orm.entity_manager]

    icse.form.type.time12:
        class: Icse\MembersBundle\Form\Type\TimeType
        tags:
            - { name: form.type, alias: time12 }

    icse.form.type.datetime12:
        class: Icse\MembersBundle\Form\Type\DateTimeType
        tags:
            - { name: form.type, alias: datetime12 }

