parameters:
#    icse_members.example.class: Icse\MembersBundle\Example

services:
    security.authentication.provider.imperial:
        class: Icse\MembersBundle\Security\Authentication\Provider\ImperialProvider
        arguments: ['', @security.user_checker, '', @security.encoder_factory, %security.authentication.hide_user_not_found%]

    icse.twig.util_extension:
        class: Icse\MembersBundle\Twig\UtilExtension
        tags:
            - { name: twig.extension } 

    kernel.listener.last_online_at_listener:
        class: Icse\MembersBundle\EventListener\LastOnlineAtListener
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onTerminate }
        arguments: [@security.context, @doctrine.orm.entity_manager] 

    kernel.listener.last_members_page_listener:
        class: Icse\MembersBundle\EventListener\LastMembersPageListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onResponse }

    icse_mailer:
        class: Icse\MembersBundle\Service\IcseMailer
        arguments: [@mailer, @css_to_inline_email_converter, %kernel.root_dir%] 

    ajax_response_gen:
        class: Icse\MembersBundle\Service\AjaxResponseGenerator

    icse.calendar_events:
        class: Icse\MembersBundle\Service\CalendarEvents
        arguments: [@doctrine.orm.entity_manager] 

#    icse_members.example:
#        class: %icse_members.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
