parameters:
#    icse_members.example.class: Icse\MembersBundle\Example

services:
    security.authentication.provider.imperial:
        class: Icse\MembersBundle\Security\Authentication\Provider\ImperialProvider
        arguments: ['', @security.user_checker, '', @security.encoder_factory, %security.authentication.hide_user_not_found%]

    icse.twig.util_extension:
        class: Icse\MembersBundle\Twig\UtilExtension
        tags:
            - { name: twig.extension } 

    icse_mailer:
        class: Icse\MembersBundle\Service\IcseMailer
        arguments: [@mailer, @css_to_inline_email_converter, %kernel.root_dir%] 

    ajax_response_gen:
        class: Icse\MembersBundle\Service\AjaxResponseGenerator

#    icse_members.example:
#        class: %icse_members.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
