parameters:
#    icse_members.example.class: Icse\MembersBundle\Example

services:
    lrotherfield.form.type.hidden_entity:
        class: Lrotherfield\Component\Form\Type\HiddenEntityType
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: form.type, alias: hidden_entity }

    icse.security.password_checker:
        class: Icse\MembersBundle\Security\Authentication\PasswordChecker
        arguments: [@security.password_encoder]

    icse.security.validator.user_password:
        class: Icse\MembersBundle\Validator\Constraints\UserPasswordValidator
        arguments: [@security.token_storage, @icse.security.password_checker]
        tags:
            - { name: validator.constraint_validator, alias: icse.security.validator.user_password }

    icse.security.authentication.provider.imperial:
        class: Icse\MembersBundle\Security\Authentication\Provider\ImperialProvider
        arguments:
            - ''
            - @security.user_checker
            - ''
            - @security.encoder_factory
            - @icse.security.password_checker
            - %security.authentication.hide_user_not_found%

    icse.twig.table_utils:
        class: Icse\MembersBundle\Twig\TableUtils
        tags:
            - { name: twig.extension }

    kernel.listener.last_online_at_listener:
        class: Icse\MembersBundle\EventListener\LastOnlineAtListener
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onTerminate }
        arguments: [@security.token_storage, @security.authorization_checker, @doctrine.orm.entity_manager]

    icse.mailer:
        class: Icse\MembersBundle\Service\IcseMailer
        arguments: [@mailer, @css_to_inline_email_converter, %kernel.root_dir%] 

    ajax_response_gen:
        class: Icse\MembersBundle\Service\AjaxResponseGenerator
        arguments: [@jms_serializer]

    icse.calendar_events:
        class: Icse\MembersBundle\Service\CalendarEvents
        arguments: [@doctrine.orm.entity_manager]

    icse.members_report_parser:
        class: Icse\MembersBundle\Service\MembersReportParser

    icse.eactivities:
        class: Icse\MembersBundle\Service\EActivities
        arguments: [%eactivities_club_id%, %eactivities_api_key%]

    icse.members_auto_updater:
        class: Icse\MembersBundle\Service\MembersAutoUpdater
        arguments: [@icse.eactivities, @icse.members_edit_hooks, @doctrine.orm.entity_manager, @validator]

    icse.committee_auto_updater:
        class: Icse\MembersBundle\Service\CommitteeAutoUpdater
        arguments: [@icse.eactivities, @doctrine.orm.entity_manager]

    icse.membership_product_auto_updater:
        class: Icse\MembersBundle\Service\MembershipProductAutoUpdater
        arguments: [@icse.eactivities, @doctrine.orm.entity_manager]

    icse.members_edit_hooks:
        class: Icse\MembersBundle\Service\MembersEditHooks
        arguments: [@icse.mailer]

    icse.form.type.time12:
        class: Icse\MembersBundle\Form\Type\TimeType
        tags:
            - { name: form.type, alias: time12 }

    icse.form.type.datetime12:
        class: Icse\MembersBundle\Form\Type\DateTimeType
        tags:
            - { name: form.type, alias: datetime12 }

    icse.form.type.text_autosuggest:
        class: Icse\MembersBundle\Form\Type\TextAutosuggestType
        tags:
            - { name: form.type, alias: icse_text_autosuggest }

